### ISSUE TITLE
Didn't work for me in Firefox and LibreWolf

### ISSUE THREAD

**Issue by gzuuus** [reyamir/nostr-connect#2]
Just testing the add-on but I cannot get it to work, it just shows a little white area under the plugin icon like this, tested in Firefox and Librewolf in Ubuntu 22.04.3 LTS 
![Screenshot from 2023-12-04 13-00-49](https://github.com/reyamir/nostr-connect/assets/116975404/9e247eff-2998-488e-b3f8-7884e5651e7b)

**Comment by reyamir** [comment]
Oh, I'm pushing new hotfix now

**Comment by gzuuus** [comment]
Works like a charm now! thanks 💜
